
---
- name: Install mongo
  block:
    # Добавим ключ репозитория для последующей работы с ним
    - name: Add APT key
      apt_key:
        id: 160D26BB1785BA38
        keyserver: keyserver.ubuntu.com

    - name: Add APT repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse
        state: present

    # Выполним установку пакетаa
    - name: Install mongodb package
      apt:
        name: mongodb-org
        state: present
    
    # Добавим права
    - name: Add priveleges
      file:
        path: "{{ item }}"
        owner: mongodb
        group: mongodb
      with_items:
        - /var/lib/mongodb
        - /tmp/mongodb-27017.sock
    
    # Удаляем строку
    - name: Correct mongod.service
      lineinfile:
        path: /lib/systemd/system/mongod.service
        state: absent
        search_string: 'Environment="MONGODB_CONFIG_OVERRIDE_NOFORK=1'
      
    # Включаем сервис
    - name: Configure service supervisor
      systemd:
        name: mongod
        enabled: yes
      tags: install
  become: true
  