---
# Установим в цикле все зависимости
- name: Install ruby and rubygems and required packages
  apt: "name={{ item }} state=latest update_cache=yes"
  with_items:
    - ruby-full
    - ruby-bundler
    - build-essential
  tags: ruby